### ISSUE TITLE
create GUI for mongo poem collections

### ISSUE THREAD

**Issue by emilywritescode** [emily-writes-poems/emily-writes-poems-processing#9]
- [x] inserting new collection - https://github.com/emily-writes-poems/emily-writes-poems-processing/issues/4
- [ ] edit poems in existing collections - emily-writes-poems/emily-writes-poems-scripts#19
  - [ ] related: edit collection - https://github.com/emily-writes-poems/emily-writes-poems-processing/issues/5
- [ ] checkbox selector for poems in DB?
- [x] #28
